#!/bin/sh
#
# compilation script for Mac systems
#

#
# Set these strings to the locations of the GLFW header directory
# and the GLFW libraries, depending upon your installation.  If
# you are using MacPorts, these are probably already set correctly;
# if you're using Homebrew, you should probably change /opt/local
# to /usr/local in both of them.  If you've installed GLFW somewhere
# else, you'll have to change them accordingly.
#
# IF YOU ARE USING SOIL, you must add "-lSOIL" to the
# 'libs' macro, and may need to add another "-I" option
# to the 'incs' macro.

incs="-I/opt/local/include"
libs="-L/opt/local/lib -lglfw"

#
# This variable contains the list of frameworks you'll need to
# compile and link against.
#
# IF YOU ARE USING SOIL, you must add "-framework CoreFoundation"
# to the 'fmwks' macro here.
#

fmwks="-framework OpenGL -framework Cocoa -framework IOKit -framework CoreVideo"

#
# Set the target; we assume that a target of "foo" will
# be compiled from either foo.c or foo.cpp
#

target="textingMain"

#
# Determine which language we're compiling
#

if [ -f $target.c ]
then
	cmd="gcc -std=c99"
	files="*.c"
else
	# for C++11, change "g++" to "g++ --std=c++11" here
	cmd="g++"
	files="*.cpp"
fi

#
# If there were command-line arguments, use them to override the default set.
#

if [ $# -gt 0 ]
then
	args="$*"
else
	args="-g -o $target"
fi

# turn on tracing so we see the compilation command
set -x

$cmd $incs $args $files $libs $fmwks
